name: hydro
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab=1.1.4
  - nodejs=12.12.0
  - numpy=1.17.2
  - matplotlib=3.1.0
  - pandas=0.24.2
  - xarray=0.12.1
  - dask=2.1
  - cartopy=0.17.0
  - netCDF4=1.5.1.2
  - rasterio=1.0.24
  - geopandas=0.5.0
  - shapely=1.6.4
  - pyproj=1.9.6
  - jupyter=1.0.0
  - geojson=2.4.1
  - pandas=0.24.2
  - seaborn=0.9
  - pysheds=0.2.6
  - mapclassify=2.1.1
  - descartes=1.1.0
  - openpyxl=3.0.1
  - ffmpeg=4.2
  - tqdm=4.32.1
  - spyder-kernels
  - scipy=1.4.1
  - cartopy=0.18.0
  - statsmodels=0.11.1
  - scikit-learn=0.23.2
